source 'https://github.com/CocoaPods/Specs.git'
target 'wangcao' do
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'YYKit'
  pod 'MBProgressHUD'
  pod 'WechatOpenSDK'
  pod 'ReactiveObjC'
  pod 'Bytedance-UnionAD'
  pod 'VTMagic', '~> 1.2.4'
  pod 'FSCalendar'
  pod 'JhtMarquee'
  pod 'MJRefresh'
  pod 'AMPopTip', '~> 1.5.3'
  pod 'LJContactManager'
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'AliyunOSSiOS'
  pod 'MQTTClient'
  pod 'GDTMobSDK'
  pod 'SigmobAd-iOS'
  pod 'TATMediaSDK'
end
